[tool.poetry]
name = "symsrv"
version = "0.1.0"
description = "Python symbol server caching proxy"
authors = ["Steven Noonan <steven@uplinklabs.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "~0"
uvicorn = "~0"
diskcache = "~5"
humanize = "~4"
httpx = "~0"
asyncio = "~3"
humanfriendly = "~10"
starlette = "~0"
anyio = "~4"
tomlkit = "~0"
websockets = "~12"
httptools = "~0"
pyyaml = "^6.0.2"

[tool.poetry.scripts]
serve = "symsrv:main"

[tool.poetry.group.dev.dependencies]
mypy = "~1"
pylint = "~3"
black = "~24"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
install_types = true
non_interactive = true
show_error_codes = true
pretty = true
ignore_missing_imports = true
exclude = ['.venv']
