# Rejects any URL with a matching substring from this list
[substring_blacklist]
patterns = [
	# Sentry requests these, even though this is a Windows symbol server
    "elf-buildid-sym-",
	"mach-uuid-sym-",
]

# Rejects any URL where the first path component (i.e. '/foo/bar' would check
# the 'foo' part of the URL) matches a string in this list
[first_path_component_blacklist]
names = [
	# Never exists upstream
	"index2.txt",

	# AMD drivers
	"AMDav1Enc32.pdb",
	"AMDav1Enc64.pdb",
	"AMDh264Enc32.pdb",
	"AMDh264Enc64.pdb",
	"AMDh265Enc32.pdb",
	"AMDh265Enc64.pdb",
	"AMDhwDecoder_32.pdb",
	"AMDhwDecoder_64.pdb",
	"amdadlx32.pdb",
	"amdadlx64.pdb",
	"amdave32.pdb",
	"amdave64.pdb",
	"amdenc32.pdb",
	"amdenc64.pdb",
	"amdgfxinfo32.pdb",
	"amdgfxinfo64.pdb",
	"amdhdl32.pdb",
	"amdhdl64.pdb",
	"amdihk32.pdb",
	"amdihk64.pdb",
	"amdlvr32.pdb",
	"amdlvr64.pdb",
	"amdmiracast.pdb",
	"amdn1b32.pdb",
	"amdn1b64.pdb",
	"amdpcom32.pdb",
	"amdpcom64.pdb",
	"amdsacli32.pdb",
	"amdsacli64.pdb",
	"amdsasrv64.pdb",
	"amduve32.pdb",
	"amduve64.pdb",
	"amdvlk32.pdb",
	"amdvlk64.pdb",
	"amdxc32.pdb",
	"amdxc64.pdb",
	"amdxcstub32.pdb",
	"amdxcstub64.pdb",
	"amdxn32.pdb",
	"amdxn64.pdb",
	"amdxx32.pdb",
	"amdxx64.pdb",
	"amf-mft-mjpeg-decoder32.pdb",
	"amf-mft-mjpeg-decoder64.pdb",
	"amf-pa-ml32.pdb",
	"amf-pa-ml64.pdb",
	"amfrt32.pdb",
	"amfrt64.pdb",
	"amfrtdrv32.pdb",
	"amfrtdrv64.pdb",
	"ati2erec.pdb",
	"atiadlxx.pdb",
	"atiadlxy.pdb",
	"atidemgy.pdb",
	"atidx9loader32.pdb",
	"atidx9loader64.pdb",
	"atidxxstub32.pdb",
	"atidxxstub64.pdb",
	"atig6pxx.pdb",
	"atig6txx.pdb",
	"atigktxx.pdb",
	"atiglpxx.pdb",
	"atimpc32.pdb",
	"atimpc64.pdb",
	"atimuixx.pdb",
	"atio6axx.pdb",
	"atioglxx.pdb",
	"atisamu32.pdb",
	"atisamu64.pdb",
	"libamdsmi_guest.pdb",
	"libamdsmi_host.pdb",

	# NVIDIA drivers
	"NvCameraAllowlisting32.pdb",
	"NvCameraAllowlisting64.pdb",
	"NvFBC.pdb",
	"NvFBC64.pdb",
	"NvIFR.pdb",
	"NvIFR64.pdb",
	"NvTelemetry64.pdb",
	"_nvngx.pdb",
	"cudnn_infer64_7.pdb",
	"nv3dappshext.pdb",
	"nv3dappshextr.pdb",
	"nvAIDVC.pdb",
	"nvAIDVCx.pdb",
	"nvAIHDR.pdb",
	"nvAIHDRx.pdb",
	"nvDecMFTMjpeg.pdb",
	"nvDecMFTMjpegx.pdb",
	"nvEncMFTH264.pdb",
	"nvEncMFTH264x.pdb",
	"nvEncMFTav1.pdb",
	"nvEncMFTav1x.pdb",
	"nvEncMFThevc.pdb",
	"nvEncMFThevcx.pdb",
	"nvEncodeAPI.pdb",
	"nvEncodeAPI64.pdb",
	"nvapi.pdb",
	"nvapi64.pdb",
	"nvcpl.pdb",
	"nvcuda32.pdb",
	"nvcuda64.pdb",
	"nvcuda_loader32.pdb",
	"nvcuda_loader64.pdb",
	"nvcudadebugger.pdb",
	"nvcuvid32.pdb",
	"nvcuvid64.pdb",
	"nvd3dum.pdb",
	"nvd3dumx.pdb",
	"nvdevtools.pdb",
	"nvdevtoolsr.pdb",
	"nvdisps.pdb",
	"nvdispsr.pdb",
	"nvdlist.pdb",
	"nvdlistx.pdb",
	"nvdlppx.pdb",
	"nvdxdlkernels.pdb",
	"nvdxgdmal32.pdb",
	"nvdxgdmal64.pdb",
	"nvgames.pdb",
	"nvgamesr.pdb",
	"nvgpucomp32.pdb",
	"nvgpucomp64.pdb",
	"nvldumd.pdb",
	"nvldumdx.pdb",
	"nvlicensings.pdb",
	"nvlicensingsr.pdb",
	"nvml.pdb",
	"nvml_loader.pdb",
	"nvngx.pdb",
	"nvngx_dlss.pdb",
	"nvofapi.pdb",
	"nvofapi64.pdb",
	"nvoglv32.pdb",
	"nvoglv64.pdb",
	"nvopencl32.pdb",
	"nvopencl64.pdb",
	"nvoptix.pdb",
	"nvppe.pdb",
	"nvppex.pdb",
	"nvptxJitCompiler32.pdb",
	"nvptxJitCompiler64.pdb",
	"nvrtum64.pdb",
	"nvshext.pdb",
	"nvsmartmax.pdb",
	"nvsmartmax64.pdb",
	"nvspcap64.pdb",
	"nvsvc64.pdb",
	"nvsvcr.pdb",
	"nvsvs.pdb",
	"nvsvsr.pdb",
	"nvui.pdb",
	"nvuir.pdb",
	"nvvitvs.pdb",
	"nvvitvsr.pdb",
	"nvvkscv64.pdb",
	"nvvm32.pdb",
	"nvvm64.pdb",
	"nvwgf2um.pdb",
	"nvwgf2umx.pdb",
	"nvwss.pdb",
	"nvwssr.pdb",
	"nvxdapix.pdb",
	"nvxdbat.pdb",
	"nvxdplcy.pdb",

	# Qt
	"Qt5Core.pdb",
	"Qt5Gui.pdb",
	"Qt5Network.pdb",
	"Qt5Positioning.pdb",
	"Qt5PrintSupport.pdb",
	"Qt5Qml.pdb",
	"Qt5QmlModels.pdb",
	"Qt5QmlWorkerScript.pdb",
	"Qt5Quick.pdb",
	"Qt5QuickControls2.pdb",
	"Qt5QuickTemplates2.pdb",
	"Qt5QuickWidgets.pdb",
	"Qt5Sql.pdb",
	"Qt5Svg.pdb",
	"Qt5WebChannel.pdb",
	"Qt5WebEngineCore.pdb",
	"Qt5WebEngineWidgets.pdb",
	"Qt5WebSockets.pdb",
	"Qt5Widgets.pdb",
	"Qt5WinExtras.pdb",
	"Qt5Xml.pdb",
	"Qt6Concurrent.pdb",
	"Qt6Core.pdb",
	"Qt6Core5Compat.pdb",
	"Qt6Gui.pdb",
	"Qt6Multimedia.pdb",
	"Qt6MultimediaQuick.pdb",
	"Qt6Network.pdb",
	"Qt6OpenGL.pdb",
	"Qt6Pdf.pdb",
	"Qt6Positioning.pdb",
	"Qt6Qml.pdb",
	"Qt6QmlModels.pdb",
	"Qt6QmlWorkerScript.pdb",
	"Qt6Quick.pdb",
	"Qt6QuickControls2.pdb",
	"Qt6QuickControls2Impl.pdb",
	"Qt6QuickDialogs2.pdb",
	"Qt6QuickDialogs2QuickImpl.pdb",
	"Qt6QuickDialogs2Utils.pdb",
	"Qt6QuickLayouts.pdb",
	"Qt6QuickTemplates2.pdb",
	"Qt6RemoteObjects.pdb",
	"Qt6Scxml.pdb",
	"Qt6Sql.pdb",
	"Qt6StateMachine.pdb",
	"Qt6Svg.pdb",
	"Qt6WebChannel.pdb",
	"Qt6WebEngineCore.pdb",
	"Qt6WebEngineQuick.pdb",
	"Qt6WebSockets.pdb",
	"Qt6Widgets.pdb",
	"Qt6Xml.pdb",
	"qcertonlybackend.pdb",
	"qgif.pdb",
	"qicns.pdb",
	"qico.pdb",
	"qjpeg.pdb",
	"qmlplugin.pdb",
	"qopensslbackend.pdb",
	"qpdf.pdb",
	"qquicklayoutsplugin.pdb",
	"qrenderdoc.pdb",
	"qschannelbackend.pdb",
	"qscxmlecmascriptdatamodel.pdb",
	"qsqlite.pdb",
	"qsvg.pdb",
	"qsvgicon.pdb",
	"qt5keychain.pdb",
	"qtga.pdb",
	"qtgraphicaleffectsplugin.pdb",
	"qtgraphicaleffectsprivate.pdb",
	"qtlabsplatformplugin.pdb",
	"qtquick2plugin.pdb",
	"qtquickcontrols2basicstyleplugin.pdb",
	"qtquickcontrols2fusionstyleplugin.pdb",
	"qtquickcontrols2implplugin.pdb",
	"qtquickcontrols2plugin.pdb",
	"qtquickcontrols2windowsstyleplugin.pdb",
	"qtquickdialogsplugin.pdb",
	"qtquicktemplates2plugin.pdb",
	"qtwebenginequickplugin.pdb",
	"quazip1-qt6.pdb",
	"quickmultimediaplugin.pdb",
	"quickwindowplugin.pdb",
	"quiethours.pdb",
	"qwbmp.pdb",
	"qwebp.pdb",
	"qwindows.pdb",
	"qwindowsvistastyle.pdb",

	# Corsair iCUE
	"ActionAssignmentsProperty.pdb",
	"ActionDescriptionUi.pdb",
	"ActionExecution.pdb",
	"ActionInterfaces.pdb",
	"ActionsConverters.pdb",
	"ActionsCueQmlPlugin.pdb",
	"ActionsUi.pdb",
	"ActionTypesRegistry.pdb",
	"ActivePropertyController.pdb",
	"ActuationCueQmlPlugin.pdb",
	"ActuationsConverter.pdb",
	"ActuationsProperty.pdb",
	"ActuationsPropertySerializer.pdb",
	"ActuationsUi.pdb",
	"AlertsCueQmlPlugin.pdb",
	"AmbidexterityController.pdb",
	"AngleSnappingController.pdb",
	"ApplicationSwitchAction.pdb",
	"ApplicationSwitchActionTypeData.pdb",
	"AppQuitManagement.pdb",
	"AssignmentsExecution.pdb",
	"Assignments.pdb",
	"AssignmentsPresetsUi.pdb",
	"AssignmentsPropertySerializer.pdb",
	"AssignmentsPropertyUpdater.pdb",
	"AssignmentTools.pdb",
	"AssociatedProgramInfo.pdb",
	"asus_plugin.pdb",
	"AttachedActionsProperty.pdb",
	"AttachedActionUi.pdb",
	"AttachedLightingsProperty.pdb",
	"AttachedLightingUi.pdb",
	"AttachedSoundsProperty.pdb",
	"AttachedSoundUi.pdb",
	"AudioDeviceConfigLib.pdb",
	"AudioHlp.pdb",
	"AudioMixerLib.pdb",
	"BatteryInfoProxy.pdb",
	"BishopController.pdb",
	"BluetoothDeviceEnumerator.pdb",
	"BragiFwUpd.pdb",
	"BrightnessAction.pdb",
	"BrightnessActionTypeData.pdb",
	"BrightnessController.pdb",
	"ButtonDebounceController.pdb",
	"CalibrationCueQmlPlugin.pdb",
	"CanvasCueQmlPlugin.pdb",
	"CanvasEffectsCueQmlPlugin.pdb",
	"ClinkProto.pdb",
	"ControllerManagerCollection.pdb",
	"CoolingCueQmlPlugin.pdb",
	"CoolingModeAction.pdb",
	"CoolingModeController.pdb",
	"CorsairAudioFWUpd.pdb",
	"CorsairCmaFwUpd.pdb",
	"Corsair.Common.Connection.pdb",
	"Corsair.Common.DevicesDefinitions.pdb",
	"Corsair.Common.pdb",
	"Corsair.Common.Shared.pdb",
	"CorsairCpuIdService.pdb",
	"Corsair.DeviceCache.pdb",
	"CorsairDeviceControlServiceAPI.pdb",
	"CorsairDeviceControlService.pdb",
	"CorsairDeviceListerService.pdb",
	"Corsair.Devices.Flextronics.pdb",
	"CorsairFwUpdMc.pdb",
	"CorsairFWUpd.pdb",
	"Corsair.GipDevices.pdb",
	"CorsairHeadsetAccessoryManager.pdb",
	"CorsairLLAccess64.pdb",
	"CorsairLLAccessLib64.pdb",
	"Corsair.Module.AsetekCooler.pdb",
	"Corsair.Module.Common.pdb",
	"Corsair.Module.CpuIdDevice.pdb",
	"Corsair.Module.CpuId.pdb",
	"Corsair.Module.DisplayAdapter.pdb",
	"Corsair.Module.Dram.pdb",
	"Corsair.Module.HidDevices.pdb",
	"Corsair.Module.PlatinumDevices.pdb",
	"Corsair.Module.ProDevices.pdb",
	"Corsair.Public.pdb",
	"Corsair.Service.Common.pdb",
	"Corsair.Service.CpuIdRemote64.pdb",
	"Corsair.Service.pdb",
	"CpuIdClient.pdb",
	"cpuidsdk64.pdb",
	"CrashDataUploader.pdb",
	"CrashHandlerLibrary.pdb",
	"CueCore.pdb",
	"CueInputEmulation.pdb",
	"CueMsiPlugin.pdb",
	"CuestyleCueQmlPlugin.pdb",
	"CurveEditorsCueQmlPlugin.pdb",
	"DashboardCueQmlPlugin.pdb",
	"DataMiningUsb.pdb",
	"DeckCueQmlPlugin.pdb",
	"DeclarationsCueQmlPlugin.pdb",
	"DeviceCommands.pdb",
	"DeviceControllers.pdb",
	"DeviceEmulation.pdb",
	"DeviceFirmware.pdb",
	"DeviceListing.pdb",
	"DeviceManager.pdb",
	"DeviceNotifications.pdb",
	"DeviceProperty.pdb",
	"DeviceProxy.pdb",
	"DeviceSettingsModule.pdb",
	"DeviceViewCueQmlPlugin.pdb",
	"DialAction.pdb",
	"DialActionsExecution.pdb",
	"DialActionsProperty.pdb",
	"DialActionsPropertySerializer.pdb",
	"DialActionUi.pdb",
	"DialCueQmlPlugin.pdb",
	"DialStateController.pdb",
	"DialZoneBrightnessController.pdb",
	"DisableAction.pdb",
	"DisableActionTypeData.pdb",
	"DisableActionUi.pdb",
	"DiscordIntegration.pdb",
	"DisplaySettingsAction.pdb",
	"DpiAction.pdb",
	"DpiCueQmlPlugin.pdb",
	"DramCueQmlPlugin.pdb",
	"EditedActionInfoUi.pdb",
	"EmptyAction.pdb",
	"EmptyActionTypeData.pdb",
	"EqPresetSwitchingAction.pdb",
	"EQSwitchAction.pdb",
	"EqualizerCueQmlPlugin.pdb",
	"EqualizerPresetsManager.pdb",
	"EventListeners.pdb",
	"FallbackManifest.pdb",
	"GameModeController.pdb",
	"GamepadCueQmlPlugin.pdb",
	"GestureAction.pdb",
	"GestureActionTypeData.pdb",
	"GestureActionUi.pdb",
	"GestureAssignmentsExecution.pdb",
	"GestureAssignmentsProperty.pdb",
	"GestureAssignmentsPropertySerializer.pdb",
	"GestureUi.pdb",
	"gigabyte_plugin.pdb",
	"GiphyCueQmlPlugin.pdb",
	"GipProtocols.pdb",
	"GoveeCueQmlPlugin.pdb",
	"govee.pdb",
	"GraphCueQmlPlugin.pdb",
	"Graph.pdb",
	"h115i_platinum.pdb",
	"HardwareLayoutController.pdb",
	"HardwareProfilesController.pdb",
	"HelpCueQmlPlugin.pdb",
	"HidEnumerator.pdb",
	"HiResTimers.pdb",
	"HorizontalScrollingAction.pdb",
	"HorizontalScrollingActionTypeData.pdb",
	"HostOperatingSystemController.pdb",
	"hueapi.pdb",
	"huestream.pdb",
	"HwPropController.pdb",
	"hx1500i.pdb",
	"iCUEDevicePluginHost.pdb",
	"iCUE Launcher.pdb",
	"iCUE.pdb",
	"icue-uninstaller.pdb",
	"iCUEUpdateService.pdb",
	"iCUEVersion.pdb",
	"iD_BD_x64_al021.pdb",
	"iD_BD_x64_cc021.pdb",
	"iD_BD_x64.pdb",
	"iD_SDK_V306.0.0.pdb",
	"IndexExcludeProxyModel.pdb",
	"ItemModels.pdb",
	"LaptopCoolingCueQmlPlugin.pdb",
	"LaunchAction.pdb",
	"LaunchActionTypeData.pdb",
	"LaunchActionUi.pdb",
	"LegacyActions.pdb",
	"LegacyEnumerator.pdb",
	"LegacyLightings.pdb",
	"LegacyModels.pdb",
	"LegacyProfiles.pdb",
	"LegacySimpleCueQmlPlugin.pdb",
	"LiftHeightController.pdb",
	"LightingLinkEffectSwitchingAction.pdb",
	"lighting_node_pro.pdb",
	"LightingsCueQmlPlugin.pdb",
	"LLAccessDeviceListing.pdb",
	"LLAccessDriverInstallTool.pdb",
	"LLAccessProto.pdb",
	"LoginCueQmlPlugin.pdb",
	"MacroAction.pdb",
	"MacroActionTypeData.pdb",
	"MacroActionUi.pdb",
	"MacroRecording.pdb",
	"MainInstallerCueQmlPlugin.pdb",
	"ManifestBuilder.pdb",
	"ManifestRegistry.pdb",
	"ManifestSharedResources.pdb",
	"MappingsActualizer.pdb",
	"MediaAction.pdb",
	"MediaActionTypeData.pdb",
	"MediaActionUi.pdb",
	"MemoryModeController.pdb",
	"MenuFn2FunctionSwapEnabledController.pdb",
	"MicrophoneAction.pdb",
	"MimicCueQmlPlugin.pdb",
	"Mimic.pdb",
	"ModelHelpers.pdb",
	"ModelsCueQmlPlugin.pdb",
	"MouseMoveCursorActionDpiController.pdb",
	"MysticLight_SDK.pdb",
	"NanoleafCueQmlPlugin.pdb",
	"nanoleaf.pdb",
	"NotificationsCueQmlPlugin.pdb",
	"NvidiaMaxineInstaller.pdb",
	"NvidiaPlugin.pdb",
	"NvMaxineCueQmlPlugin.pdb",
	"PackageManager.pdb",
	"PerformanceCueQmlPlugin.pdb",
	"PhilipsHueCueQmlPlugin.pdb",
	"philips_hue.pdb",
	"PictureSettingsCueQmlPlugin.pdb",
	"PluginDevice.pdb",
	"PowerPerformanceAction.pdb",
	"PowerStateListener.pdb",
	"ProfilesCueQmlPlugin.pdb",
	"Profiles.pdb",
	"ProfileSwitchingAction.pdb",
	"ProfileSwitchingActionTypeData.pdb",
	"ProfileSwitchingActionUi.pdb",
	"PropertyActualizerStorage.pdb",
	"ProtocolHelpers.pdb",
	"qmlplugin.pdb",
	"QuickLightingZonesCueQmlPlugin.pdb",
	"RemapAction.pdb",
	"RemapActionTypeData.pdb",
	"RemapActionUi.pdb",
	"RotationConfigurationSwitchAction.pdb",
	"ScreenEffectsCueQmlPlugin.pdb",
	"ScreenSwitchingAction.pdb",
	"ScreenSwitchingActionTypeData.pdb",
	"ScreenSwitchingActionUi.pdb",
	"ScufControllerLibrary.pdb",
	"SdkKeysFilterHandler.pdb",
	"Sensors.pdb",
	"SessionWatcher.pdb",
	"SettingsCueQmlPlugin.pdb",
	"SimpleCueQmlPlugin.pdb",
	"SlipstreamCueQmlPlugin.pdb",
	"StylePartsCueQmlPlugin.pdb",
	"SurroundStateChangeAction.pdb",
	"SystemDevice.pdb",
	"TextAction.pdb",
	"TextActionTypeData.pdb",
	"TextActionUi.pdb",
	"TiltGesturesCueQmlPlugin.pdb",
	"TouchScreenActionsExecution.pdb",
	"TouchscreensCueQmlPlugin.pdb",
	"TouchScreensLib.pdb",
	"TrackJoggingAction.pdb",
	"TrackJoggingActionTypeData.pdb",
	"TrayCueQmlPlugin.pdb",
	"TrianglesChannelCueQmlPlugin.pdb",
	"TutorialsCueQmlPlugin.pdb",
	"UninstallDevices_x64.pdb",
	"UniqueDeviceIds.pdb",
	"UniversalKey.pdb",
	"UsbDeviceListing.pdb",
	"usersession.pdb",
	"UtilityCueQmlPlugin.pdb",
	"vengeance_rgb_pro.pdb",
	"VerticalScrollingAction.pdb",
	"VerticalScrollingActionTypeData.pdb",
	"VibrationCueQmlPlugin.pdb",
	"VirtualKeyboardCueQmlPlugin.pdb",
	"VoicemodAction.pdb",
	"WeightTuningCueQmlPlugin.pdb",
	"WindowCueQmlPlugin.pdb",
	"WinlockStateController.pdb",
	"WirelessPollingRateController.pdb",
	"WizardsCueQmlPlugin.pdb",
	"WmiDeviceListing.pdb",
	"XmpCueQmlPlugin.pdb",
	"ZoomAction.pdb",
	"ZoomActionTypeData.pdb",

	# General
	"ffmpeg.dll.pdb",
	"libavcodec-58.pdb",
	"libavformat-58.pdb",
	"libavutil-56.pdb",
	"swresample-4.pdb",
	"avcodec-59.pdb",
	"avformat-59.pdb",
	"avutil-57.pdb",
]

[suffix_blacklist]
suffixes = [
	".src.zip",
	".dbg",
	".db_",
]
